config/routes.rb
Rails.application.routes.draw do
  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'experience', to: 'pages#experience'
  get 'resume', to: 'pages#resume'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def experience
  end

  def resume
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <li class="nav item">
    <a class="nav-link" href="#">My Site!</a>
    </li>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to "Home", root_path, class:'nav-link'%>
        </li>
        <li class="nav-item">
        <%= link_to "About", about_path, class:'nav-link'%>
        <li> 
        <%= link_to "Experience", experience_path, class:'nav-link'%>
        </li>
        <li> 
        <%= link_to "Resume", "https://docs.google.com/document/d/1xhoQ6Mlh2-tLVOEITl2fh8_m310QxCT3uGKdVnkn9nc/edit", class:'nav-link'%>
        </li>
        <li>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MySite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
  <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Bolanle Adisa</title>
    <link href="https://fonts.googleapis.com/css2?family=Akaya+Telivigala&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="styles.css">
</head>

<style>body {background-color: lightblue;}</style>

<body>
    <p>
        <br>
    <h2>Hobbies</h2>
    <p>
        <br>
        Travelling is my favorite thing to do! I am a very inquisitive person so traveling helps me explore and provide answers to a lot of the unanswered questions I have about the world.
        As a 19 year old college student, I have not had the oppotunity to do much exploring but I hope to do a lot of that in the future. I am Nigerian and being from a country
        with a beautiful and rich culture makes me value the culture of others as well. I hope to be able to see the beauty of other countries around the world. I also love going on short road
        trips to places nearby like Houston and Dallas.
        <br>
        <br>
        I love to work out; I started going to the gym consistently this year. My friends and family are very important to me so I love to spend time with them. I love to teach people and also learn. 
        I like to keep myself busy so I am always working on a project. Lastly, I love to binge-watch TV shows!
        <br>
        <br>
        Feel free to contact me using the links below!
        <br>
        <br><img src="/assets/hiking.jpg" style="padding-bottom:10px;"/>
        <img src="/assets/roadtrip.jpg" style="padding-bottom:10px;"/>
        <img src="/assets/kayaking.jpg" style="padding-bottom:10px;"/>
    
</body>

<footer>
    <p>CONTACT</p>
    <a href="https://github.com/bolanle-adisa">You can find me on GitHub here</a>
    <br>
    <a href="https://www.linkedin.com/in/bolanleadisa">You can find me on Linkedin here</a>
</footer>

</html>

app/views/pages/experience.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Bolanle Adisa</title>
    <link href="https://fonts.googleapis.com/css2?family=Akaya+Telivigala&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="styles.css">
</head>

<style>body {background-color: lightblue;}</style>

<body>
    
    <p>
        <br>Hello again!
        <br>
        <br>
        I am a currently Sophomore majoring in Computer Science and Mathematics at Huston-Tillotson University, Austin, Texas. Prior to college, I had zero coding experience but I am now proficient
        in JAVA and C++. I have worked as an IT Technician at my University for about a year now and my time working there has allowed me to see a side of Tech that I was not exposed to before.
        I have gained hands-on experience dealing with computer hardware while performing installations, fixing networking issues, restarting servers and tending to the technical difficulties students at
        my University experience daily. 
        <br>
        <br>
        I have worked on a number of projects since I started coding. Below are some major projects:
        <br>
        <br>
        - Designed a Notepad GUI application using JAVA
        <br>
        - Designed a Testing GUI application usine JAVA
        <br>
        - Designed an ATM interface client application using C++ that enables users to perform tasks such as Register, Log-in, Deposit, Withdraw, Check balance, Exit and other custom features.
        <br>
        - Designed a Lottery Picker GUI application using JAVA
        <br>
        - Designed a Tabbed Pane Calculator GUI application using JAVA
        <br>
        - Designed a Password Checker GUI application using JAVA
        <br> 
        <br>
        The projects above can be viewed on my GitHub page. 
        <br>
        <h2>Aspirations</h2>
    
        In the future, I hope to do a lot of front-end work with computer software because I want to be able to provide value to others. As a very creative person, I would love my work
        to be seen by anyone who interacts with a brand or project I am associated with. This way, I can interact with my end customers and finally be able to not only create new technology but also 
        improve how technology is used around world.
        <br>
        <br>
        Find me on my professional platforms like LinkedIn and GitHub using the links at the bottom of the page. 
    </p>
    </p>
        Thanks again for visiting my website!
    </p>
        <br>
    
</body>

<footer>
    <p>CONTACT</p>
    <a href="https://github.com/bolanle-adisa">You can find me on GitHub here</a>
    <br>
    <a href="https://www.linkedin.com/in/bolanleadisa">You can find me on Linkedin here</a>
</footer>

</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Bolanle Adisa</title>
    <link href="https://fonts.googleapis.com/css2?family=Akaya+Telivigala&display=swap" rel="stylesheet">
    <link rel="stylesheets" href="stylesheet/styles.css">
</head>

<style>body {background-color: lightblue;}</style>

    <div class="grid-2">
        <div class="section-1">
        <img src="/assets/logo.jpg" style="padding-bottom:5px;"/>
        
            <h2>Bolanle Adisa</h2>
            <p>Huston-Tillotson University</p>
            <p>Austin, Texas</p>
                                                                                                                                 
        </div>
        <div class="section-2">
            <h2>A little about me!</h2>
            <p>
                Hello! Welcome to my portfolio.</p>
                <p>I am a Sophomore majoring in Computer Science and Mathematics at Huston-Tillotson University, Austin, Texas. I love to learn new things and travel. In the future, I hope to use my Computer Science degree and all the knowledge I acquire along the way to improve the way technology is used in the world. 
                Currently, my goal is to be proficient in various programming languages in order to expand my knowledge in Computer Science and Technology and gain experience that would be useful to me in the work force.
                <p>Thank you for visiting my portfolio!
                </p>
            </p>  
        </div>
    </div>

</body>

<footer>
    <p>CONTACT</p>
    <a href="https://github.com/bolanle-adisa">You can find me on GitHub here</a>
    <br>
    <a href="https://www.linkedin.com/in/bolanleadisa">You can find me on Linkedin here</a>
</footer>

</html>

app/views/pages/resume.html.erb
<h1>Pages#resume</h1>
<p>Find me in app/views/pages/resume.html.erb</p>